version: '3.8'
services:
    php-apache-environment:
        container_name: apache-php
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 7077:80
    db:
        container_name: database
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: elmeow
            MYSQL_PASSWORD: inipasswordmeow
        ports:
            - "7100:90"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8000:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db